// @ts-nocheck
import { AfterViewInit, Component, OnDestroy, ViewEncapsulation } from '@angular/core';
@Component({selector:'app-home',encapsulation:ViewEncapsulation.None,standalone:true,templateUrl:'./home.component.html',styleUrl:'./home.component.scss'})
export class HomeComponent implements AfterViewInit, OnDestroy {
 private cleanup: (()=>void)|undefined;
 ngAfterViewInit(){
 this.cleanup = (()=>{const story=document.querySelector('.scroll-story'),demo=document.querySelector('.web-demo'),title=document.querySelector('#story-title'),description=document.querySelector('#story-description');const reduced=matchMedia('(prefers-reduced-motion: reduce)');let pending=false;const stages=[['Todo empieza<br>con una idea.','Damos estructura a lo que quieres contar.'],['Una web que se adapta.<br>A ti. Y a tu cliente.','Desarrollamos una experiencia para móvil, tablet y ordenador.'],['Y seguimos<br>cuidando de ella.','Mantenemos el servidor de la web que hemos creado para ti.']];function draw(){pending=false;const r=story.getBoundingClientRect(),range=Math.max(1,story.offsetHeight-innerHeight),p=Math.max(0,Math.min(1,-r.top/range));const mobile=innerWidth<700;const phase=Math.min(2,Math.floor(p*3));story.dataset.phase=phase;title.innerHTML=stages[phase][0];description.textContent=stages[phase][1];const build=Math.min(1,p*4);demo.style.setProperty('--build',build);demo.style.setProperty('--narrow',Math.max(0,Math.min(1,(p-.34)*5)));const a=Math.max(0,Math.min(1,(p-.68)*5));story.style.setProperty('--server',a);document.querySelectorAll('.story-progress span').forEach((el,i)=>el.classList.toggle('active',i===phase));const hero=document.querySelector('.identity');if(hero&&!reduced.matches)hero.style.transform=`translateY(${Math.min(30,scrollY*.06)}px) scale(${1-Math.min(.06,scrollY*.00008)})`;if(reduced.matches){demo.style.setProperty('--build',1);demo.style.setProperty('--narrow',0);story.style.setProperty('--server',1)} }function queue(){if(!pending){pending=true;requestAnimationFrame(draw)}}addEventListener('scroll',queue,{passive:true});addEventListener('resize',queue);reduced.addEventListener('change',queue);draw();const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.service-list article,.steps article,.contact h2').forEach(el=>{el.classList.add('reveal');observer.observe(el)});return ()=>{removeEventListener("scroll",queue);removeEventListener("resize",queue);reduced.removeEventListener("change",queue);observer.disconnect();};})();

 }
 ngOnDestroy(){this.cleanup?.();}
}
